function shuffleArray(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
}

var quotes = [
    "prodali su nase snove judini sinovi",
    "jebem li gi",
    "Брате ово си много добро урадио, тотално описује југ Србије. Ова фамозна креација није само песма већ и немилосрдна истина! Само да је нама ракије да наздравимо… Поздрав из Књажевца, живела Србија! 🇷🇸",
    "svadbe su sa okidacima<br>sarane sa trubacima<br>narodnjaci iz bembare<br>kajle, trenerke, zene prelepe",
    "ODAKLE SAM JA",
    "dzaba copor vuk se dzumara ne boji",
    "jeste spremni da vam zapalimo auto i kuci<br>jos nam kolo vode potomci udbasa<br>mladi savuljic gusla kao visnjic",
    "al kad pogeldas ukupno to su strane pare",
    "ma nije dobro",
    "inace u zgradu prekuoputa dosli ukrainci<br>a kurac nije ipak to dobro<br>i pare u dzep bato<br>sve pojacamo<br>dignemo cene<br>nek dolaze<br>ma cuti, ko ih jebe<br>bitno je ko je kakav coviJek",
    "stvarno si blagosloven",
    "bara zvoni znaci davim se lovi",
    "fantazija",
    "gari garo sto garila nisi",
    "prvi beli narod",
    "dok maljutke jezde<br>gledajmo tu nuklearnu zoru<br>ne cuje se<br>na nebu iznad severodonjecka padaju zvezde<br>i just need to go to vojvodina",
    "dzarulja hahahhahahhahha",
    "pita emil stari u kolko da se nadju glave<br>a ja gledam kako govna plove tokom mlave<br>dolko je lose da ljudima na ulici vicem zipa<br>aj sto smrdi vec i za oci jace stipa",
    "u kolima dusko kada prdnez prdez jako<br>pomolim se zemli miloj otvori mi se rako",
    "oj dusko kurcino stara<br>pamti te iz raske gara",
    "hamzo stari jaka ti je ruka<br>kad puknes turka njemu unuk kuka",
    "za vosu nasu pivo u casu<br>nek se vosin barjak vije od sombora do nere mije<br>i zbog slavnog grgeteka hopova i kovilja<br>i zbog slavnih vojvodjana canka i stevana<br>a tiii veseli se lalo rode lalo rode zbog slobode<br>ogrijalo suuunce sa banata polja ravna<br>zasijale svetinje fruskogorske od davna",
    "okolina raske je bas luda",
    "cemu ti zemlja avganistana<br>cemu nasa bol i nasa slava<br>prastajte gore vi ste videle<br>biografija nasa-maleni blok<br>psiholozi se guraju, sad su u modi<br>al ne podleze nauci daleki istok<br>odlazimo, odlazimo, odlazimo<br>.",
    "Let the great feast commence<br>The earth is thirsty, it longs for blood.<br>we are ready for war<br>the red sun is licking our helmets<br>in the stillness of the morning we sharpen our swords<br>blood has spilled into the balkan territory",
    "otvaram se jako - balkan ekspres",
    "za tu diplomu polozicu zivot u borbu<br>nebeska srbija vas ceka<br>sta je pukovnik il pokojnik",
    "ko da je jul<br>jbt trava vec krenula da se susi",
    "sace nova tura da ugusi budj",
    "sad sam pojeo pola jebene vekne budjavog hleba",
    "javi se gs<br>javi se brate skimsi<br>javi se brate klisi<br>pola ulici na di si<br>nema te<br>de si ti bato<br>stari as",
    "deste cure deste cure evo inzenjera<br>crven dzemper i kosulja bijela",
    "ju ja vec mislio da sam krenuo da klizim<br>ne razumem sta se pise<br>ko da mi se oci razisle",
    "zakucace opet johanovo srce<br>vrbovace me bia<br>sad sam zapadni agent<br>pozdravi mladu bebu<br>ma druze ja tada vec radim u operativi<br>to je moja mracna strana",
    "jos samo u japankama nekog da vidim<br>u firmi<br>lik u kosulji sorcu i papuce bos bez carapa<br>sta radi ovaj jebani narod",
    "moj burazer nocas je daleko<br>ko da za me skoci ako krene neko",
    "jedna srpska suza hiljadu albanaca",
    "biseri iz blata u rimsko doba",
    "pricaju dva cigana jesi ikad lizo prljvu picku? jesam, a jesi lizo cistu? sta ima tu danse lize",
    "big tits small feet",
    "sedamo za rucak i cale dolazi mami ajde da mi zavijes ranu i ona mu nasprica necima i krene da piri da se brze osusi<br>kaze matori duvaj duvaj, dobro duvas",
    "kaze mi portir u nedelju ti vodi racuna sta se desava gore",
    "Cause Jesus, he knows me<br>And he knows I'm right",
    "neka ide sve do vraga i ratovi i paktovi,<br>ako neko jos cezne za time nek se seti- HIROSIME",
    "niko ne zna sta su prave muke da tovari slepera na ruke",
    "orgonski top da kupim<br>i raznesem srbiju u tri picke materine",
    "dosli iz citaonice neki da mu traze da upali klimu<br>on slaze da ne moze<br>mrzi ga da ustanea hahahbabab",
    "bio malo sa portirom dragancetom danas<br>nikad gori<br>prdi, noge ko trudnuca kad se poradja oslonio na sto<br>kancelarija smrdi na rakiju<br>a on gleda kako bi tresao studentkinje<br>i pazi sad matorog lazova<br>bila tu jedna u citki sto ga podjebava stalno<br>a dragance se nalozio kao majmun<br>kaze oce kurca, prcacu je kad tas<br>ja reko sto lazes a on ju je kao uvatio na kvarno za sisu a ona voli<br>stoka",
    "its an evil world we live in",
    "NECU PREKO NISANA DA GLEDAM RUSE",
    "ti si demonizivan prijatelju<br>pusis travu<br>pitam a prijatelju ti radis u debilani a<br>upalim povracku<br>razmisljam da odem",
    "zivela srbija, za srbiju ubijađ<br>ordenja, barjaci, perjanice<br>da faks moze da me dobije na fer sad bi bio bokser a ne obivan ker",
    "to je sad pitanje da li predigru racunas u cin snosaja",
    "probo sam i u moru al nije mi islo",
    "preko nisana da gledam ruse<br>znaci necu",
    "pitaj papu<br>jel njihov stepinac ravan nasem rastku<br>za koga si 43 vrsljao po bosni<br>nece na sokola svraka<br>nece cava na junaka",
    "latini su stare varalice<br>papstvo dribla na ekumenizam<br>latini su stare varalice<br>nece cava na junaka<br>nece na sokola svraka<br>necu. preko. nisana. da. gledam. ruse.<br>necu",
    "NECU PREKO NISANA DA GLEDAM RUSE<br>U SE I U SVOJE KLJUSE<br>NECU PREKO NISANA DA GLEDAM RUSE<br>NECU PREKO NISANA DA GLEDAM RUSE",
    "ko se smeje onda kada place,<br>onaj ludi srbin sto na jace vazda skace",
    "nabadanje u lobanju<br>znas sve<br>gledam emisiju o pecanju<br>na plitvicama u zAgrebu<br>lole<br>stare metaklije<br>merak<br>najjace",
    "lazem da uspomene vise ne postoje, al moje srce je sehara ja tamo cuvam blago svoje",
    "vole nas narod kosidbu pa to ti je",
    "kad na kampu povezem cetiri pet piva, vise nisam deda tad sam hevi prda<br>prdim ko epilepticar u nesvest padam",
    "od svoje ljubavi prema coveku umro je bog",
    "omnost koja je ovaplocena u necemu je tek korisna",
    "umni ljudi ne mogu sami po sebi",
    "organizatori, prevoznici, snabdevaci...",
    "picke jedne, lihvari...",
    "eh da nije mjesec posta braco moja...",
    "ma sve pobacajte sa mosta",
    "vidim da placu, kazem BILO JE DOSTA",
    "eh da nije mjesec posta ja bi nocas muski popio",
    "malo sunkice pred spavanje",
    "BICE UKRAINA RUSKA<br>IMA BOGA<br>NA POGRESNOM SAM PUTU AL MENE TO NE ZANIMA",
    "DODAJ MI PUSKU SINE SPIDOM ZAKUNDACIME",
    "NA SEBI NE STEDIM<br>na sebi ne stedim<br>bacicu monitor kroz prozor",
    "DROGIRAM SE SVIM I SVACIM<br>SMRKACIM<br>SMRKACIM<br>SMRKACIM",
    "to je ono sto pricam svi su vukovi, nema dobre ovce vise",
    "isto pre neki dan u pekaru rol virsla 120<br>kad nisam puko samar gazdi",
    "a sa je ovo mrmoti u sestom danu idemo jace od vas gta novi sad imamo sve citove sta se desava ovo drzimo u sedam dimenzija afteri po igraonicama pika se kanter dota opasnija od dopa ljudi ovo vise nema smisla morate svi komplet na lecenje znaci spid i bajadere",
    "ah te duge polarne noci",
    "ja razden v savejtskom sajuze, sdelan ja v sssr",
    "ru bad ua bad war good",
    "druze rucnu sam povuko samog sebe se plasim",
    "ha ha ha ko jos veruje u bradatog ciku na nebu",
    "slava ukraini",
    "inace desio se obrt neki u poslednjih sto godina<br>nekad su svi bili ovce<br>a sada svi oce vukovi da budu<br>jagnje bozije i te price<br>niko vise ne zna da slusa",
    "najokupiraniji ljudi na svetu<br>dogovoricemo se za cast",
    "al sam se juce najezio idem ka labaru i neka zena mi pretrcava put al sjebano ko iz nekog mog sna<br>ju al me prosla jeza",
    "na pogresnom sam putu al mene to ne zanima<br>sahrani me na jugu ako ove noci ja umrem mlad",
    "zeludac nikad jaci",
    "kakvo bildersko govno sam israo",
    "ali sve sto se radi s po kurca zna se",
    "ako da bog<br>mozda najjadniji poklic u istoriji<br>mekan onako",
    "svaki novi dogadjaj sto se desi kao da mi urusi mali delic razumevanja sveta",
    "dobijamo bizona na fruskaci<br>samo ne znam gde ce stati ti bizoni",
    "jesi pito dal je to to<br>ili mislis da je to to",
    "ajmo tusiranje jetre da padne",
    "dace bog",
    "marva je da se vodi<br>nema dalje to treba ponavljati kao molitvu ujutro i uvece",
    "blagosloveni su oni koji ne vide",
    "glavni seljak na rejvu vicem ajoj mama",
    "prvih pet ne mogu da jedem ni da spavam",
    "sprepucam se ne bude mi dobro 15 dana",
    "crni cerak fula gang bezim od policije<br>jedna od lepota postojanja",
    "u fazonu jak ko konj glup ko kurac",
    "ja jesam",
    "i am the devil",
    "odem u nedelju na najlon i naletim na stand sps-a<br>a oni pustili neke idj hitove i doveli neke spermulje tu da igraju kao<br>a penzioneri se nalozili pa ih propituju kao<br>a zapravo dzepni bilijar",
    "eee u moje vreme se to srafcigerom radilo<br>ovim novima je med i mleko",
    "bolje zvuci sunkica nego slaninica",
    "opet je BOG srbina svog na noge stavio",
    "jedan vikend se lomi a gladaju se ceo mesec prica",
    "oladi glavu posle ispita<br>popi vopi",
    "POSLEDNJI POZDRAV DISKRETNOM HEROJU",
    "guzna pancerota❤️",
    "ovome treba da tezimo vredna braco moja<br>jak ko konj glup ko kurac<br>a goal worth striving for<br>jbg treba i sutra nesto raditi<br>nekad su babe pazi ovu ludost kad se rodi zensko dete bile u fazonu nek je zivo i zdravo<br>pravim rupe gde gazim<br>im the cotizen of the earth<br>i jos nesto muka mi je vise prica izadjite na izbore i glasajte<br>nema od toga leba<br>stokom treba vladati<br>nisu za bolje<br>nije ta prica<br>alahambra nas ceka",
    "mentorova neka drugarica iz firme me zove mali<br>au braco koje price zivim",
    "srbi rusi braca zauvek<br>nas i rusa 300 miliona druze",
    "volece kad budu govorili luk i mleko",
    "bitches on my mind",
    "ima neki kod podhodnika svira tamo daleko na violini<br>moment inspiracije",
    "koju jebavo sam mlad<br>tamo mi spalise kurvu<br>bez kurvi daleko u kurcu zivim ja<br>i opet ponosno klikcem zivela fuksetina",
    "snajper velike moci legija<br>laki mitraljez arkan<br>mobilni transporter pesadije kapetan dragan",
    "Адмира́л фло́та Сове́тского Сою́за Кузнецо́в",
    "idemo u stratosferu braco",
    "straight from the source<br>znas me",
    "mi smo krajina ledjima pravimo hlad",
    "ne zelim da privlacim paznju na noge<br>a cuje se",
    "pomirimo=pokorimo",
    "oni su kao dede u psima<br>ja sam ex yu<br>trebo si me slusati",
    "vreme je da se spilhozne zamene za kombinezone<br>sto smo se zajebavali zajebavali smo se",
    "ma kakva ljubav nek te jebe ko te placa",
    "God speed and happy hunting",
    "kakav zapad kakve picke materine<br>srbuj makar opanke jeo",
    "sam bi sebi po glavi skako sam bi sebi razbio glavu u svakoj rapsravi sam ja u pravu<br>I WEAR MY SUNGLASSES AT NIGHT",
    "evo granulo sunce bratani<br>moramo u crkvu da se pomolimo za sunce",
    "Не треба гледати на запад. Ми за њих никада нећемо бити добри јер смо православци.",
    "poslednji pozdrav diskretnom heroju",
    "puko sam<br>au<br>ne znam jel bacas foricu ili sam sizofren postao",
    "fever dream ne secam se<br>galerija fresaka<br>koja galerija<br>na spidu sam",
    "zamislite ovo braco<br>ovu najtuzniju od svih prica<br>da zapravo vise nikad nece biti civilnih zrtvi<br>vec ce se samo boriti vlast i vojske<br>a mi kao ovce samo cutimo i primamo od sledecih<br>najtezi od svih zivota",
    "previse je dobrih ljudi na ovoj planeti",
    "racunica je jednostavna<br>oni cekaju zapad<br>mi cekamo boreju",
    "ma lukav+lud>sve ostalo",
    "ma druze zakon ludjeg ne jaceg",
    "najlepse vreme nas ceka<br>brus je otkopcan<br>nema vise nazad<br>kocka je bacena<br>najlepsi zivot",
    "znas da sam taj likslab im zglob<br>slabo tkivo<br>lepo fotelja topla cokolada i genocid lagani",
    "zivot damo kraljeve moje ne damo",
    "covek ima previse vremena da smislja",
    "izasao na ulicu popusio kurcinu<br>a cutao si, verovao, nadao se, glasao<br>granice crtaju pobednici<br>mi smo ta prica",
    "zove turija kao nekada<br>zovu grobovi mojih predaka<br>zove ponovo supljikac stevo<br>zove sremica, moje grabovo",
    "sta je fora kao da te forsiraju da budes uzvisena licnosr a ti samo oces hleb",
    "source: i made it up",
    "samo sklopi okice<br>i slomi mi ime<br>samo sklopi okice i slomi mi ime",
    "I'm an Alabama Nigger and I wanna be free",
    "I wanna be white more and more<br>so I can bitch at the nigger next door",
    "mislim slika je eurokrem iliti jing jang<br>eurokrem ili jing jang",
    "idem da se pomolim gospodinu i spavanje<br>sve to broji neko",
    "larpujem da sam kakovan u parku<br>ma da<br>malo i tata bi sine priva<br>a ja idem iza zbuna da se volim",
    "da se ne mucis",
    "lepi dani mog detinsjtva<br>malo hleba puno piva<br>bolje spid uzmi samo",
    "i to sto kazes<br>ne treba preterivati",
    "ubio me vetar<br>i bi kurcina",
    "mani me tih prica govna se pustaju ne preciscena<br>ko zna zasto je to dobro",
    "novi sade zbogom nikad ti nisam sudio<br>i nisam sebi sudio ma gde bi se budio<br>nekad kuci srecan nekad sve izgubio",
    "code red<br>nedostaje mi mrma nedostaje mi mrma pucicu od spida moram da mrdam",
    "Tipični znaci treme bili bi drhtanje ruku, gutanje ili hvatanje<br>vazduha dubokim uzdahom. U akademskim komunikacijama ove gestove treba savladati.",
    "pokreni tu sinusoidu zgutaj knedlu i gledaj kako oroboros okrece svoj krug",
    "pored najdublje rupe je najvisa planina",
    "neko gore broji sve poene<br>fora je sto mi nemamo cula za njegove informacije<br>retki su oni koji osete a jos redji koji posle razumeju to<br>ja sam video jednom takvog  coveka<br>posle liturgije izlazim i neki stariji covek zamnom i bukvalno mu oci sijaju zlatom<br>razumeo je pricu al tad sam bio mlad i premalo znao<br>nisam imao sta sa ga pitam samo sam osetio da kroz njega bog deluje<br>al vremenom i ja sam dobio usi i znam da broji",
    "mora krug da se okreve",
    "sve sto je zivo mora umreti a sto je mrtvo oziveti",
    "e dobri moji setite se ovih reci: blazeno je sve ono sto ustaje i leze jer zivi u skladu sa zmijom",
    "kanalski beton feels warm at night",
    "U skupstinskom holu drzim zolju i bombu,<br>odajte poslednju postu diskretnom heroju.<br>Znoj kaplje po papiru, poslednju pisem zelju,<br>Ostajte mi zdravi, verni nasem htenju.<br>I kad umrem za istinu, ispunite moju volju,<br>poljubite za mene neku Srbiju bolju!",
    "Овде има рима свима клинцима за пример<br>За све усијане главе да се охладе и смире<br>Нестали су кодекси, остали су комплекси<br>Победе су порази, а исходи су потресни<br>Зато стани мало, размисли<br>Шта ћеш тиме постићи",
    "Svirajte mi jesen stiže dunjo moja, jesen rana,<br>nek zazvone tambure u transu",
    "Ej, Vojvodino, od plača, od đubreta i od kolača,<br>a vere četir, a peta ciganska, a šesta iz tambure riče!",
    "oprostite mojoj mladoj zelji sto je jos gruba i nespretna pa ne zna lepse da vam govori<br>da kazaljka lupa po 8000 ko nikad do sad<br>zato bakulajneri lezite na tu papucicu da mu ga damo u blokadu<br>ceo ovaj svet je beskrajan niz vrata koja se na kraju spajaju u krug<br>to je krug koji moramo nastaviti da vrtimo<br>mi treba da otvaramo put onome od sutra a iskupljujemo onog od juce",
    "spremam uputstvo za srbiju<br>spremam zaprsku za mnogo ozbiljniju corbu veruj mi",
    "moram okameniti srce opet<br>mekan sam previse",
    "I setite se jos jednom reci davno zaboravljenih.  Samo kada se na pitanje \"Ko je najveci covek koji je ikad postojao?\" odgovori sa \"Saksonac koji mrzi!\", znacemo da je Hiperboreja dostignuta.  Ne Julije Cezar, ne Aleksandar Veliki!",
    "crno pleme=semitsko pleme",
    "spremite se<br>izrigacu se ovde da mi supak na usta izadje<br>al dok ne krenem drugde da povracam",
    "zna cica sta valaj",
    "ako bog da po zlu se pamtilo<br>bog vas blagoslovio braco moja nek se melje jos vise<br>al neka<br>walk hand in hand into extinction",
    "kaze i kad pustis stare brkove ne rastu stare no nove dlake",
    "da sine novo sunce staro mora zaci",
    "Quo vadis, aida?",
    "WAKE UP<br>its not real wake up<br>tu smo upali u alternativni univerzum",
    "pisem ovo dok pokusavam da zaspim i zamisljam da sam spasao svet",
    "natopicemo svet znojom i krvlju",
    "iznova i iznova",
    "Nach Ostland sie zu tragen, sie will sie muss dorthin.<br>Die Besten sind geblieben, uns ander'n brach die Kraft<br>Die Grenzwacht hielt im Osten<br>Die Grenzwacht hielt im Osten",
    "ne sme izumreti snaga",
    "celicenje u vatri<br>zaradi na kari<br>svanulo je<br>dobro jutro",
    "tuga je sto nemaju hrabrosti da mrze",
    "oce li se ikad sresti<br>tvoja noc i moja zora",
    "ma druze ja sam glavu ugano oko 2 jebes nogu",
    "teski su lanci",
    "pamet u glavu kurac u sake",
    "ispadas iz price ko iz picke tampon",
    "vremece se brojati od kad je saksonac poceo da mrzi",
    "majonez na burek?",
    "zahvalan sam sto sam ziv",
    "od svoje samilosti umro je covek<br>osvetite me braco moja<br>ispovracajte se na grob",
    "zatvori krug",
    "sa kakvim demonima se borim u snovima ovo mi dodje ko sladoled<br>dobro jutro",
    "nemoj dovoditi kurvetine",
    "znam da nisam trebo tako i da nije moralno, pare na since placam solarno",
    "oprostite mi braco<br>krug mora da nastavi da se okrece<br>lord giveth lord taketh away",
    "i nastavlja se krug zmija jede sebi rep",
    "jebes boga koji oce da stalno misle na njega",
    "paprikas<br>kiseli kupus<br>kiseli kupus i paprikas, braco moja, kupus i paprikas ne pice i burgeri",
    "znas moje ime ali ne i moju pricu",
    "BICU UVEK ISTI SVATI TO BRE PA MANI ME SA TIM PITANJEM DOKLE",
    "dok ne sarani me inat",
    "hiperboreja se ne definise ona se oseca",
    "sunce izlazi na istoku a zalazi na zapadu",
    "prica je teska za one koji ne veruju",
    "hypermasculine need to be schizo",
    "druze niko ne zna kako je na vrhu",
    "The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents. We live on a placid island of ignorance in the midst of black seas of infinity, and it was not meant that we should voyage far. The sciences, each straining in its own direction, have hitherto harmed us little; but some day the piecing together of dissociated knowledge will open up such terrifying vistas of reality, and of our frightful position therein, that we shall either go mad from the revelation or flee from the light into the peace and safety of a new dark age.",
    "once more unto the breach my friends<br>idemo opet",
    "nemate usi da cujete sta pricam zato vam ih treba razbiti da slusate ocima",
    "the only thing im fucking is retarded",
    "spremite se<br>ostalo je jos malo do velikog podneva",
    "ponedeljak je sultani moji vredni",
    "pojedite suzavce a cekice lomite o kolena",
    "nek kokodacu i brbocu vasi protivnici, ali sta mari vetar sto neko kasljuca, kako bi taj mogao podneti silinu njegove pobedonosne srece<br>zato neka vas ostar planinski vetar oduva maglu i donese miris juznoga mora",
    "ocvrsnite vasa srca da od samilosti ne bi umrli",
    "ovo je danas moja molitva: nek most opet zaroni u dunav",
    "braco moja budite mi oci danas i pokazite im gde dunav ljubi beton, zelim vam svu srecu ovog sveta",
    "nema povlacenja nema predaje",
    "HELIKOPTER HELIKOPTER<br>PARA KOPTER PARA KOPTER<br>OTIMA i PLJACKA<br>nocima se otima<br>NE ZNAM SAMO ZOVI GA<br>kojeg covika<br>ZOVI COVIKA ZOVI ZOVI COVIKA"
]

shuffleArray(quotes)